### ISSUE TITLE
2.- CLIENTES

### ISSUE THREAD

**Issue by anacid** [anacid/Monte-Carmelo#2]
Como el fichero de clientes a pasar es muy extenso, hemos pensado por ejemplo, coger los clientes a los que se les ha facturado durante los últimos cincos. O si se prefiere pasamos todos.

**Comment by anacid** [comment]
Pedido a Conchita

**Comment by anacid** [comment]
El prefiere que pasamos todos los clientes, sino es mucho problema, porque hay casos en los que igual hace tiempo que no han pedido nada y de nuevo vuelven a comprar algún libro, y así no tiene que estar pidiendoles todos los datos de nuevo.

**Comment by gregorioruiz** [comment]
Preparado el proceso de importación a un temporal
Ahora falta hacer una segunda criba de los que ya están en su actual fichero de clientes
Y luego hacer el proceso final de importación para los que marque.
