### ISSUE TITLE
3.- TITULOS

### ISSUE THREAD

**Issue by anacid** [anacid/Monte-Carmelo#3]
Separar en varias pestañas los que son libros, de los CD para poder incorporar nosotras los que faltan.

**Comment by anacid** [comment]
Pedido a Conchita. Los ocho primeros dígitos de los títulos son fijos. Conchita en el programa tiene puesto los trece dígitos, pero en Madrid por lo visto solo tiene 3numeros-1numero.

**Comment by anacid** [comment]
Perfecto, no hay ningún problema él nos hará todas las pestañas que necesitemos.

**Comment by gregorioruiz** [comment]
Ya debería estar en tu correo un fichero ZIP con su excel. Si tienes dudas para descomprimirlo me lo dices.
También se lo ha mandado a Conchita. 
Lo podemos mirar un segundo y comentar si vale la pena que Conchita ponga las familias antes de importarlo.

![ScreenClip.png](https://zube.io/files/anacid/84066a06a7000ea39e2680afec080bad.png)

**Comment by gregorioruiz** [comment]
Los libros se dan de alta en la familia L43, de nombre EDITORIAL DE ESPIRITUALIDAD
Queda pendiente si Feli consigue información sobre cuales de los autores son liquidables y cuales no.

**Comment by gregorioruiz** [comment]
Ya le han contestado a Feli:
De momento hago las pruebas con lo que tengo, sin poner los autores y cuando estén ya lo actualizaremos.

**Comment by gregorioruiz** [comment]
Enviado a Conchita informes con la importación para comentar cómo mejorarla.
